// This file is generated by rust-protobuf 2.14.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `game_request.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_14_0;

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct GameRequest {
    // message fields
    pub gameName: ::std::string::String,
    pub numPlayers: i32,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a GameRequest {
    fn default() -> &'a GameRequest {
        <GameRequest as ::protobuf::Message>::default_instance()
    }
}

impl GameRequest {
    pub fn new() -> GameRequest {
        ::std::default::Default::default()
    }

    // string gameName = 1;


    pub fn get_gameName(&self) -> &str {
        &self.gameName
    }
    pub fn clear_gameName(&mut self) {
        self.gameName.clear();
    }

    // Param is passed by value, moved
    pub fn set_gameName(&mut self, v: ::std::string::String) {
        self.gameName = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_gameName(&mut self) -> &mut ::std::string::String {
        &mut self.gameName
    }

    // Take field
    pub fn take_gameName(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.gameName, ::std::string::String::new())
    }

    // int32 numPlayers = 2;


    pub fn get_numPlayers(&self) -> i32 {
        self.numPlayers
    }
    pub fn clear_numPlayers(&mut self) {
        self.numPlayers = 0;
    }

    // Param is passed by value, moved
    pub fn set_numPlayers(&mut self, v: i32) {
        self.numPlayers = v;
    }
}

impl ::protobuf::Message for GameRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.gameName)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.numPlayers = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.gameName.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.gameName);
        }
        if self.numPlayers != 0 {
            my_size += ::protobuf::rt::value_size(2, self.numPlayers, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.gameName.is_empty() {
            os.write_string(1, &self.gameName)?;
        }
        if self.numPlayers != 0 {
            os.write_int32(2, self.numPlayers)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> GameRequest {
        GameRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "gameName",
                    |m: &GameRequest| { &m.gameName },
                    |m: &mut GameRequest| { &mut m.gameName },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "numPlayers",
                    |m: &GameRequest| { &m.numPlayers },
                    |m: &mut GameRequest| { &mut m.numPlayers },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<GameRequest>(
                    "GameRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static GameRequest {
        static mut instance: ::protobuf::lazy::Lazy<GameRequest> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(GameRequest::new)
        }
    }
}

impl ::protobuf::Clear for GameRequest {
    fn clear(&mut self) {
        self.gameName.clear();
        self.numPlayers = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for GameRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GameRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x12game_request.proto\x12\0\"9\n\x0bGameRequest\x12\x12\n\x08gameName\
    \x18\x01\x20\x01(\tB\0\x12\x14\n\nnumPlayers\x18\x02\x20\x01(\x05B\0:\0B\
    \0b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
